### PR TITLE
various updates to the docs

### PR DESCRIPTION
**Pull request by RichardHill**
Various updates to the documentation.

How to debug a function ( in Go )
How to restore a function
Various error messages
Updating some of the images

### CODE REVIEW

**Review by tomaswarynyca — COMMENTED** [review]
@RichardHill  I made some changes to improve the display!
What do you think?

**Comment by RichardHill** [comment]
The commute do improve the presentation. 

I prefer that when we have some CLI command that it is a code block that the user can easily copy to the clipboard ?

**Comment by tomaswarynyca** [comment]
There I made the commands in code blocks

But I don't quite like the way it looks, maybe @onattech  can help to give a nice format.
image

**Comment by RichardHill** [comment]
> quite

The visual is consistent with the other parts of the site and I'd like to get this live today.

**Pull request merged**
